import { parseVisualization, type Visualization } from "@under-glass/core";

/**
 * The canonical playground fixture mirrors the production-facing PopChoice
 * runtime. Delivery infrastructure is intentionally omitted so the primary
 * recommendation flow remains legible.
 */
export const POPCHOICE_VISUALIZATION: Visualization = parseVisualization({
  schemaVersion: 1,
  nodes: [
    {
      id: "browser",
      label: "Browser",
      assetId: "browser-asset",
      position: { x: -9, z: -2.75 },
      quarterTurns: 0,
    },
    {
      id: "web",
      label: "Web",
      assetId: "service-asset",
      position: { x: -6.5, z: -2.75 },
      quarterTurns: 1,
      groupId: "product-runtime",
    },
    {
      id: "workers",
      label: "Workers",
      assetId: "worker-asset",
      position: { x: -0.5, z: -2.75 },
      quarterTurns: 0,
      groupId: "product-runtime",
    },
    {
      id: "backoffice",
      label: "Backoffice",
      assetId: "dashboard-asset",
      position: { x: -6.5, z: 0.25 },
      quarterTurns: 0,
      groupId: "product-runtime",
    },
    {
      id: "bull-board",
      label: "Bull Board",
      assetId: "dashboard-asset",
      position: { x: -3.5, z: 0.25 },
      quarterTurns: 0,
      groupId: "product-runtime",
    },
    {
      id: "movie-discovery",
      label: "Movie Discovery",
      assetId: "discovery-asset",
      position: { x: -0.5, z: 0.25 },
      quarterTurns: 0,
      groupId: "product-runtime",
    },
    {
      id: "redis",
      label: "Redis · BullMQ",
      assetId: "queue-asset",
      position: { x: -3.5, z: 3.5 },
      quarterTurns: 0,
      groupId: "data-observability",
    },
    {
      id: "postgres",
      label: "PostgreSQL · pgvector",
      assetId: "database-asset",
      position: { x: 2.5, z: 3.5 },
      quarterTurns: 0,
      groupId: "data-observability",
    },
    {
      id: "telemetry-stack",
      label: "Telemetry Stack",
      assetId: "telemetry-asset",
      position: { x: -1.5, z: 6.25 },
      quarterTurns: 0,
      groupId: "data-observability",
    },
    {
      id: "grafana",
      label: "Grafana",
      assetId: "dashboard-asset",
      position: { x: 2.5, z: 7.25 },
      quarterTurns: 0,
      groupId: "data-observability",
    },
    {
      id: "openai-api",
      label: "OpenAI API",
      assetId: "provider-asset",
      position: { x: 5.75, z: -6 },
      quarterTurns: 0,
    },
    {
      id: "tmdb-api",
      label: "TMDB API",
      assetId: "provider-asset",
      position: { x: 5.75, z: 5.5 },
      quarterTurns: 0,
    },
  ],
  groups: [
    {
      id: "product-runtime",
      label: "Product Runtime",
      bounds: { minX: -8.25, minZ: -4.5, maxX: 1.25, maxZ: 1.75 },
    },
    {
      id: "data-observability",
      label: "Data & Observability",
      bounds: { minX: -5.25, minZ: 2, maxX: 4.25, maxZ: 8.5 },
    },
  ],
  connections: [
    {
      id: "browser-web",
      label: "HTTPS",
      source: { nodeId: "browser" },
      target: { nodeId: "web" },
      direction: "oneWay",
      routeAnchors: [],
    },
    {
      id: "web-redis",
      label: "Enqueue work",
      source: { nodeId: "web" },
      target: { nodeId: "redis" },
      direction: "oneWay",
      routeAnchors: [],
    },
    {
      id: "redis-workers",
      label: "BullMQ jobs",
      source: { nodeId: "redis" },
      target: { nodeId: "workers" },
      direction: "oneWay",
      routeAnchors: [],
    },
    {
      id: "workers-postgres",
      label: "Persist results",
      source: { nodeId: "workers" },
      target: { nodeId: "postgres" },
      direction: "oneWay",
      routeAnchors: [],
    },
    {
      id: "web-postgres",
      label: "SQL + pgvector",
      source: { nodeId: "web" },
      target: { nodeId: "postgres" },
      direction: "bidirectional",
      routeAnchors: [],
    },
    {
      id: "workers-openai",
      label: "OpenAI inference",
      source: { nodeId: "workers" },
      target: { nodeId: "openai-api" },
      direction: "oneWay",
      routeAnchors: [],
    },
    {
      id: "workers-tmdb",
      label: "TMDB metadata",
      source: { nodeId: "workers" },
      target: { nodeId: "tmdb-api" },
      direction: "oneWay",
      routeAnchors: [],
    },
    {
      id: "backoffice-postgres",
      label: "Admin data",
      source: { nodeId: "backoffice" },
      target: { nodeId: "postgres" },
      direction: "bidirectional",
      routeAnchors: [],
    },
    {
      id: "backoffice-redis",
      label: "Enqueue work",
      source: { nodeId: "backoffice" },
      target: { nodeId: "redis" },
      direction: "bidirectional",
      routeAnchors: [],
    },
    {
      id: "bull-board-redis",
      label: "Queue inspection",
      source: { nodeId: "bull-board" },
      target: { nodeId: "redis" },
      direction: "oneWay",
      routeAnchors: [],
    },
    {
      id: "movie-discovery-tmdb",
      label: "Discover movies",
      source: { nodeId: "movie-discovery" },
      target: { nodeId: "tmdb-api" },
      direction: "oneWay",
      routeAnchors: [],
    },
    {
      id: "movie-discovery-openai",
      label: "Embeddings",
      source: { nodeId: "movie-discovery" },
      target: { nodeId: "openai-api" },
      direction: "oneWay",
      routeAnchors: [],
    },
    {
      id: "movie-discovery-postgres",
      label: "Upsert catalog",
      source: { nodeId: "movie-discovery" },
      target: { nodeId: "postgres" },
      direction: "oneWay",
      routeAnchors: [],
    },
    {
      id: "web-telemetry",
      label: "Telemetry",
      source: { nodeId: "web" },
      target: { nodeId: "telemetry-stack" },
      direction: "oneWay",
      routeAnchors: [],
      styleKey: "telemetry",
    },
    {
      id: "workers-telemetry",
      label: "Telemetry",
      source: { nodeId: "workers" },
      target: { nodeId: "telemetry-stack" },
      direction: "oneWay",
      routeAnchors: [],
      styleKey: "telemetry",
    },
    {
      id: "backoffice-telemetry",
      label: "Telemetry",
      source: { nodeId: "backoffice" },
      target: { nodeId: "telemetry-stack" },
      direction: "oneWay",
      routeAnchors: [],
      styleKey: "telemetry",
    },
    {
      id: "telemetry-grafana",
      label: "Metrics · logs · traces",
      source: { nodeId: "telemetry-stack" },
      target: { nodeId: "grafana" },
      direction: "oneWay",
      routeAnchors: [],
      styleKey: "telemetry",
    },
  ],
  openingView: {
    cameraMode: "isometric",
    quarterTurns: 1,
    center: { x: -1.5, z: 1.25 },
    groundSpan: 16,
  },
});
