import { parseVisualization, type Visualization } from "@under-glass/core";

export const PROJECT_GRAPH_VISUALIZATION: Visualization = parseVisualization({
  schemaVersion: 1,
  nodes: [
    {
      id: "browser",
      label: "Browser",
      assetId: "browser-asset",
      position: { x: -6.5, z: -0.5 },
      quarterTurns: 0,
      groupId: "edge",
    },
    {
      id: "gateway",
      label: "Gateway",
      assetId: "service-asset",
      position: { x: -4, z: -0.5 },
      quarterTurns: 1,
      groupId: "edge",
    },
    {
      id: "api",
      label: "API",
      assetId: "service-asset",
      position: { x: -1, z: -1 },
      quarterTurns: 0,
      groupId: "core",
    },
    {
      id: "queue",
      label: "Queue",
      assetId: "queue-asset",
      position: { x: 1.5, z: -1 },
      quarterTurns: 0,
      groupId: "core",
    },
    {
      id: "worker",
      label: "Worker",
      assetId: "service-asset",
      position: { x: 4, z: -1 },
      quarterTurns: 3,
      groupId: "core",
    },
    {
      id: "database",
      label: "Database",
      assetId: "database-asset",
      position: { x: 6.5, z: -1 },
      quarterTurns: 0,
      groupId: "core",
    },
    {
      id: "storage",
      label: "Storage",
      assetId: "queue-asset",
      position: { x: 1.5, z: 2 },
      quarterTurns: 1,
      groupId: "core",
    },
    {
      id: "observe",
      label: "Observe",
      assetId: "browser-asset",
      position: { x: 4.5, z: 2 },
      quarterTurns: 2,
      groupId: "core",
    },
  ],
  groups: [
    {
      id: "edge",
      label: "Edge",
      bounds: { minX: -8, minZ: -3, maxX: -3, maxZ: 2.5 },
    },
    {
      id: "core",
      label: "Core",
      bounds: { minX: -2.5, minZ: -3.5, maxX: 8, maxZ: 4 },
    },
  ],
  connections: [
    {
      id: "browser-gateway",
      label: "",
      source: { nodeId: "browser" },
      target: { nodeId: "gateway" },
      direction: "oneWay",
      routeAnchors: [],
    },
    {
      id: "gateway-api",
      label: "",
      source: { nodeId: "gateway" },
      target: { nodeId: "api" },
      direction: "oneWay",
      routeAnchors: [],
    },
    {
      id: "api-queue",
      label: "",
      source: { nodeId: "api" },
      target: { nodeId: "queue" },
      direction: "oneWay",
      routeAnchors: [],
    },
    {
      id: "queue-worker",
      label: "",
      source: { nodeId: "queue" },
      target: { nodeId: "worker" },
      direction: "oneWay",
      routeAnchors: [],
    },
    {
      id: "worker-database",
      label: "",
      source: { nodeId: "worker" },
      target: { nodeId: "database" },
      direction: "oneWay",
      routeAnchors: [],
    },
    {
      id: "queue-storage",
      label: "",
      source: { nodeId: "queue" },
      target: { nodeId: "storage" },
      direction: "oneWay",
      routeAnchors: [],
    },
    {
      id: "queue-observe",
      label: "Telemetry",
      source: { nodeId: "queue" },
      target: { nodeId: "observe" },
      direction: "oneWay",
      routeAnchors: [],
      styleKey: "telemetry",
    },
    {
      id: "database-observe",
      label: "Telemetry",
      source: { nodeId: "database" },
      target: { nodeId: "observe" },
      direction: "oneWay",
      routeAnchors: [],
      styleKey: "telemetry",
    },
  ],
  openingView: {
    cameraMode: "isometric",
    quarterTurns: 0,
    center: { x: 0, z: 0.25 },
    groundSpan: 10,
  },
});
